---

- name: Install prerequisites
  yum: name={{ item }} state=latest
  with_items: "{{ prerequisites }}"

- name: Update pip
  pip: name=pip state=latest

- name: Install shade
  pip: name=shade

- name: Destroy all openstack_vms
  os_server:
    state: absent
    availability_zone: "{{ openstack.availability_zone }}"
    key_name: "{{ openstack.key_name }}"
    flavor: "{{ openstack.nodes_flavor }}"
    security_groups: "{{ openstack.security_groups }}"
    auto_ip: "{{ openstack.auto_ip }}"
    name: "{{ item }}"
    image: "{{ openstack.image }}"
    timeout: 300
  when: item != 'localhost'
  with_items: "{{ groups['all'] }}"
