
- debug: var=server_id
  tags: abc

- name: Copy docker-compose.yml to host
  template: src=zookeeper.yml.j2 dest=~/zookeeper.yml

- name: Create zookeeper services
  shell: docker-compose -f ~/zookeeper.yml up -d