
- set_fact: server_id = 0 
  when: server_id is not defined

- set_fact: server_id={{ server_id | int + 1 }}

- name: Create zookeeper services
  docker_container:
    name: zookeeper
    image: confluentinc/cp-zookeeper:3.0.1
    state: present
    recreate: yes
    ports:
      - 2181:2181
    env:
      ZOOKEEPER_SERVER_ID: {{server_id}}
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: {% for node in groups['zookeeper']  %}"{{ node }}:2888:3888"{% if not loop.last %};{% endif %}{% endfor %} 
    network_mode: host
      
    
