---
# tasks file for consul
- name: Turn off iptables (firewalld)
  service: name=firewalld state=stopped
  ignore_errors: true

- name: Disable selinux
  selinux: state=disabled

- name: Create consul folder
  file: path=/opt/consul state=directory

- name: Copy files to host
  template: src=docker-compose.yml.j2 dest=/opt/consul/docker-compose.yml

- name: Compose consul server
  shell: cd /opt/consul && docker-compose -f docker-compose.yml up -d
