

- name: Copy consul agent config
  template: src=agent_base_config.json.j2 dest=/etc/consul.d/agent_base_config.json
  become: true

- name: Copy consul elasticsearch test
  template: src=elasticsearch.service.json.j2 dest=/etc/consul.d/elasticsearch.service.json
  when: inventory_hostname in groups['elasticsearch']
  become: true

- name: overwrite /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf backup=yes
  become: true
