---
# tasks file for consul-agent
#  - name: Get list of all VMs
#    os_server_facts:
#      timeout: 300
#    delegate_to: localhost
#
#  - name: Generate consul IP list
#    set_fact:
#      consul_ips: "{{ consul_ips | default({}) | combine({item.private_v4} )}}"
#    with_items: "{{ openstack_servers }}"
#    when: item.name in groups['consul']
#    delegate_to localhost
#    no_log: True

  - debug: var=vars

  - name: Turn off iptables (firewalld)
    service: name=firewalld state=stopped
    become: true

  - name: Disable selinux
    selinux: state=disabled
    become: true

  - name: Copy Consul binary if it doesnt exist
    copy: src=consul dest=/usr/sbin/consul mode=u+rwx
    become: true

  - name: Create consul directory
    file: path=/etc/consul.d state=directory
    become: true

  - name: Copy consul system service
    template: src=consul.service.j2 dest=/etc/systemd/system/consul.service
    become: true

  - name: reload systemd
    command: /usr/bin/systemctl daemon-reload
    become: true

  - include: agent.yml
    when: inventory_hostname not in groups['consul']

  - include: server.yml
    when: inventory_hostname in groups['consul']

  - name: Start consul service
    service: name=consul state=restarted enabled=yes
    become: true

  - name: Register with consul primary server
    command: /usr/sbin/consul join {{ item }}
    with_items: "{{ consul_ips }}"
    when: inventory_hostname not in groups['consul']
    become: true
