
- name: Create directories for kafka
  file: path={{ item }} state=directory recurse=true owner=12345 group=12345 mode=0777
  become: true
  with_items:
    - /var/lib/kafka/data
    - /opt/oss/kafka

- name: Copy docker-compose.yml to host
  template: src=kafka.yml.j2 dest=/opt/oss/kafka/kafka.yml

- name: Compose kafka docker containers
  shell: docker-compose -f /opt/oss/kafka/kafka.yml up -d
 
- name: Register kafka service in consul
  uri:
    url: http://{{consul_ips[0]}}:8500/v1/catalog/register
    method: PUT
    body: "{{ lookup('template','kafka.service.json.j2') }}"
    status_code: 200
    body_format: json