
- name: Create directories for kafka
  file: path={{ item }} state=directory recurse=true owner=12345 group=12345 mode=0777
  become: true
  with_items:
    - /var/lib/kafka/data
    - /opt/oss/kafka

- name: Copy docker-compose.yml to host
  template: src=kafka.yml.j2 dest=/opt/oss/kafka/kafka.yml

- name: Create kafka
  shell: docker-compose -f /opt/oss/kafka/kafka.yml up -d

- name: Copy consul kafka service definition
  template: src=kafka.service.json.j2 dest=/etc/consul.d/kafka.service.json
 
- name: Register consul service
  uri:
    url: https://{{consul_ips[0]}}:8500/v1/catalog/register
    method: PUT
    body: "{{ lookup('template','kafka.service.json.j2') }}"
    status_code: 201
    body_format: json

# - name: Restart consul service
 #   service: name=consul state=restarted enabled=yes
 #   become: true
