
- name: Generate random password for elastic user
  shell: openssl rand -hex 8
  register: es_pwd

- name: Create user
  uri:
    url: http://{{ bind_address }}:9200/_xpack/security/user/{{ user }}
    method: POST
    user: "elastic"
    password: "changeme"
    body: "{{ lookup('template', 'user.json.j2') }}"
    body_format: json
    return_content: yes
  when: create == true


- name: Update user
  uri:
    url: http://{{ bind_address }}:9200/_xpack/security/user/{{ user }}/_password
    method: PUT
    user: "elastic"
    password: "changeme"
    body: "{{ lookup('template', 'pwd.json.j2') }}"
    body_format: json
    return_content: yes
  when: create != true


- name: Save password in consul for user
  uri: 
    url: "http://{{ consul_ips[0] }}:8500/v1/kv/{{ customer_id }}/settings/elasticsearch/{{ user }}/password" 
    method: "PUT" 
    body: "{{ es_pwd.stdout }}"
    status_code: 200
