---
# tasks file for elastic

 #- debug: var=vars

 - name: update vm_max_map_count
   command: /sbin/sysctl -w vm.max_map_count=400000

 - name: Install Elasticsearch Repo Key
   rpm_key: key=https://packages.elastic.co/GPG-KEY-elasticsearch state=present
   tags: 'elastic-repo'

 - name: Install Elasticsearch Server Repos
   copy: src=elastic.repo dest=/etc/yum.repos.d/elastic.repo
   tags: 'elastic-repo'

 - name: Install Curator Repo
   copy: src=curator.repo dest=/etc/yum.repos.d/curator.repo
   tags: 'elastic-repo'

 - name: Install Java
   yum: name=java-1.8.0-openjdk-headless state=present

 - name: Install Elasticsearch
   yum: name=elasticsearch-5.0.0 state=present

 - name: Create Elasticsearch data directories
   file: path=/mnt/es/data state=directory owner=elasticsearch

 - name: Create Elasticsearch log directories
   file: path=/mnt/es/logs state=directory owner=elasticsearch

 - name: Elasticsearch config file edits
   template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml

 - name: Ensure elastic environment variables are set.
   blockinfile:
       dest: /etc/sysconfig/elasticsearch
       marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK -->"
       block: |
               MAX_OPEN_FILES=65535
               MAX_LOCKED_MEMORY=unlimited
               ES_JAVA_OPTS="-Xms4g -Xmx4g"

 - name: Start Elasticsearch Service
   service: name=elasticsearch state=restarted enabled=true

 - name: Install Elasticsearch x-pack
   command: /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack
   ignore_errors: True

 - name: Restart Elasticsearch Service for x-pack
   service: name=elasticsearch state=restarted enabled=true

 - include: curator.yml
   tags: curator
