
- name: Get master node todo count
  uri: 
    url: "http://{{consul_ips[0]}}:8500/v1/kv/{{ customer_id }}/settings/elasticsearch/master_node_count_todo?raw" 
    return_content: yes
  register: master_node_count_todo

- name: Get data node todo count
  uri: 
    url: "http://{{consul_ips[0]}}:8500/v1/kv/{{ customer_id }}/settings/elasticsearch/data_node_count_todo?raw" 
    return_content: yes
  register: data_node_count_todo

- name: Run compose if todo > 0
  include: compose.yml
  vars: 
    node_type: "master"
    node_id: "{{ master_node_count_todo.content }}"
    is_master_node: true
    is_data_node: false
    min_port: 9200
    max_port: 9299
  when: "{{ master_node_count_todo.content | int }} > 0"

- name: Run compose if todo > 0
  include: compose.yml
  vars: 
    node_type: "data"
    node_id: "{{ data_node_count_todo.content }}"
    is_master_node: false
    is_data_node: true
    min_port: 9300
    max_port: 9399
  when: "{{ data_node_count_todo.content | int }} > 0"

- name: Set todo master count
  uri:
    url: "http://{{consul_ips[0]}}:8500/v1/kv/{{ customer_id }}/settings/elasticsearch/master_node_count_todo"
    method: PUT
    body: "{{ master_node_count_todo.content | int  - 1}}"  

- name: Set todo data count
  uri:
    url: "http://{{consul_ips[0]}}:8500/v1/kv/{{ customer_id }}/settings/elasticsearch/data_node_count_todo"
    method: PUT
    body: "{{ data_node_count_todo.content | int - 1}} "  
