#Install Docker

- name: Install yum utils
  yum: name=yum-utils state=present

- name: Add docker repo
  copy: src=docker.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: Install Docker
  yum: name=docker-engine-1.12.3 state=present

- name: Create Docker service folder
  file: path={{ item }} state=directory recurse=yes
  with_items:
    - "/etc/systemd/system/docker.service.d"

- name: Create docker service
  copy: src=docker.conf dest=/etc/systemd/system/docker.service.d/docker.conf

- name: systemd daemon reload
  shell: sudo systemctl daemon-reload

- name: Start docker service
  service: name=docker.service enabled=yes state=started

- name: Add '{{ remote_user }} ' to docker group
  user: name='{{ remote_user }}' groups=docker append=yes

- name: Wait for docker
  wait_for: port=2375 delay=10 timeout=60

- name: Install docker compose
  get_url: 
    url: https://github.com/docker/compose/releases/download/1.8.0/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/bin/docker-compose
    mode: 0755
  become: true
