#Before installing confirm the consul server IP addresses are correct in ansible/inventory/<site>/group_vars/all
 # Elasticsearch cluster deployment with consul agents
# To create a new cluster in VA1 and to deploy to that cluster use openstack.yml
- name: Get master node count
  hosts: localhost
  tasks:
    - name: Get master node count
      uri: url="http://{{consul_ips[0]}}:8500/v1/kv/{{ customer_id }}/settings/elasticsearch/master_node_count?raw" return_content=yes
      register: master_node_count

    - name: Get data node count
      uri: url="http://{{consul_ips[0]}}:8500/v1/kv/{{ customer_id }}/settings/elasticsearch/data_node_count?raw" return_content=yes
      register: data_node_count

    - name: Set todo master count
      uri:
        url: "http://{{consul_ips[0]}}:8500/v1/kv/{{ customer_id }}/settings/elasticsearch/master_node_count_todo"
        method: PUT
        body: "{{ master_node_count.content }}"

    - name: Set todo data count
      uri:
        url: "http://{{consul_ips[0]}}:8500/v1/kv/{{ customer_id }}/settings/elasticsearch/data_node_count_todo"
        method: PUT
        body: "{{ data_node_count.content }}"

- name: print values
  hosts: localhost
  tasks:
    - debug: msg={{master_node_count.content}}
    - debug: msg={{data_node_count.content}}

- name: Install Elasticsearch
  remote_user: "{{ remote_user }}"
  hosts: elasticsearch
  become: true
  tags: elastic
  roles:
    - docker
    - consul-agent
    - elastic
  environment:
      CONSUL: "{{consul_ips[0]}}:8500"
      CUSTOMER_ID: "{{ customer_id }}"
      DATACENTER: "{{ datacenter }}"

- name: Install dashboard
  remote_user: "{{ remote_user }}"
  hosts: dashboard
  become: true
  tags: dashboard
  roles:
    - docker
    - consul-agent
    - dashboard
  environment:
      CONSUL: "{{consul_ips[0]}}:8500"
      CUSTOMER_ID: "{{ customer_id }}"
      DATACENTER: "{{ datacenter }}"