- name: Deploy Openstack nodes
  hosts: localhost
  become: true
  roles:
     - gce
  environment: "{{ gce_environment }}"
     

#After the nodes are deployed, update inventory/<environment>/group_vars/all to add consul server IP and then run site.yml
