---
# Elasticsearch cluster deployment with consul agents
# To create a new cluster in VA1 and to deploy to that cluster use openstack.yml

  - name: Install zookeeper
    remote_user: "{{ remote_user }}"
    hosts: zookeeper
    tags: zookeeper
    roles:
      - consul-agent
      - docker
      - zookeeper
      - kafka