- name: Deploy Openstack nodes
  hosts: localhost
  become: true
  roles:
     - nova-client
     - instance-destroy
     - instance-create
  environment: "{{ envionment }}"

  - include: consul-server.yml
  - include: elasticsearch.yml

