- name: Deploy Openstack nodes
  hosts: localhost
  become: true
  roles:
     - nova-client
     - instance-destroy
     - instance-create
  environment: "{{ environment }}"

- name: Deploy Openstack nodes
  become: true
  hosts: all
  tags: volume
  roles:
     - instance-configure
  environment: "{{ environment }}"

#After the nodes are deployed, update inventory/<environment>/group_vars/all to add consul server IP and then run site.yml
