---
# This playbook deploys the whole application stack in this site.  

#- name: Update /etc/hosts on control machine
#  hosts: localhost
#  remote_user: "{{ remote_user }}"
#  tags: 'etc-hosts'
#  roles:
#    - etc-hosts
#  environment: "{{ env_os }}"

- name: Install consul server
  remote_user: "{{ remote_user }}"
  hosts: all
  tags: consul
  roles:
    - consul

- name: Elasticsearch Nodes
  hosts: elasticsearch
  become: true
  tags: elastic

  roles:
    - elastic
