---
# This playbook deploys the whole application stack in this site.  

- name: Deploy Openstack nodes
  hosts: localhost
  become: true
  roles:
#     - nova-client
#     - instance-destroy
#     - instance-create
  environment: "{{ env_os }}"

- name: Update /etc/hosts on control machine
  hosts: localhost
  remote_user: "{{ remote_user }}"
  tags: 'etc-hosts'
  roles:
    - etc-hosts
  environment: "{{ env_os }}"

- name: Install consul agent
  remote_user: "{{ remote_user }}"
  hosts: elasticsearch
  roles:
    - consul-agent

- name: Elasticsearch Nodes
  hosts: elasticsearch
  remote_user: cloud-user
  become: true
  tags: elastic

  roles:
    - elastic
